### ISSUE TITLE
Adding question and ans to leetcode challenges

### ISSUE THREAD

**Issue by KUndn** [KUndn/leetcode30days_challenge#1]
Add question along with solutions .

**Comment by VishalAmbavade** [comment]
Hi @KUndn, can I make PR directly with the question and solution? Or should I create an issue first?

**Comment by KUndn** [comment]
> Hi @KUndn, can I make PR directly with the question and solution? Or should I create an issue first?

you can make a PR directly.

**Comment by stellaharmony** [comment]
Hi @KUndn , Can you assign me this issue?

**Comment by KUndn** [comment]
@mbhole1857 you have been assigned.

**Comment by KUndn** [comment]
@VishalAmbavade @mbhole1857  also star the repository
